apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: note-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /mininote-v1
          backend:
            serviceName: mininote-service
            servicePort: 8080
        - path: /mininote-v2
          backend:
            serviceName: mininote-new
            servicePort: 8080




