apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mininote-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /?(.*)
          backend:
            serviceName: mininote-service
            servicePort: 8080




