# Deployment YAML definition

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mininote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mininote
  template:
    metadata:
      labels:
        app: mininote
    spec:
      containers:
        - name: mininote-java
          image: helayoty/mininote-java:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
---
# Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: mininote-service
spec:
  selector:
    app: mininote
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer