debug: true

server:
    contextPath: /tmp

azure:
  cosmosdb:
    databaseName: philly-mininote
    uri: https://philly-mininote.documents.azure.com:443/
    key: mSDbXG6ZHxqEa3ZNT0YxLnuABYRHlDgU9XdrsQFItVmGtVYKHiLFqyqTdrORQcvbhla1HCQtGzR9NlIlTdBRUg==
    secondaryKey: HzqN611uFiHYUU9AcuupKHjnzpamx0pLF6BlDxnw3ozSdwcdpqE0iR9GGmz27CAtZxUn3XL3LqFlYn7YaB2EHw==
    populateQueryMetrics: true

spring:
  servlet: #optional
    multipart:
      max-file-size: 1048576KB
      max-request-size: 1048576KB
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftlh

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

